name: "Caches gradle & Kotlin/Native cleanup"
description: "Caches gradle & Kotlin/Native cleanup"
inputs: {}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
        rm -f ~/.konan/cache
