// WARNING: File autogenerated DO NOT modify
// https://www.khronos.org/registry/OpenGL/api/GLES2/gl2.h
@file:Suppress("unused", "RedundantUnitReturnType", "PropertyName")

package com.soywiz.kgl

import kotlinx.cinterop.COpaquePointer
import platform.windows.GetProcAddress
import platform.windows.HMODULE
import platform.windows.LoadLibraryA
import platform.windows.wglGetProcAddress

private val OPENGL32_DLL_MODULE: HMODULE? by lazy { LoadLibraryA("opengl32.dll") }

internal actual fun glGetProcAddressAnyOrNull(name: String): COpaquePointer? =
    wglGetProcAddress(name) ?: GetProcAddress(OPENGL32_DLL_MODULE, name)

actual class KmlGlNative actual constructor() : NativeBaseKmlGl() {

}
