name: "TEST SNAPSHOT"

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    # https://crontab.guru/#0_0_*_*_4
    # “At 00:00 on Thursday.”
    - cron: "0 0 * * 4"

env:
  # https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/kotlin/kotlin-compiler/1.5.255-SNAPSHOT/
  FORCED_KOTLIN_VERSION: "1.7.255-SNAPSHOT"
  SKIP_KORGE_SAMPLES: true

jobs:
  build:

    runs-on: ubuntu-latest
    #continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Start gradle
      run: ./gradlew
    - name: Testing JVM
      run: ./gradlew --no-daemon jvmTest
    - name: Testing JS
      run: ./gradlew --no-daemon jsNodeTest
