name: TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SKIP_KORGE_SAMPLES: true

jobs:
  test:
    timeout-minutes: 60

    runs-on: ubuntu-latest
    #continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Start gradle
      run: ./gradlew
    - name: Testing JVM
      run: ./gradlew --no-daemon jvmTest
    - name: Testing Node JS
      run: ./gradlew --no-daemon jsNodeTest
    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()
    #  with:
    #    name: JUnit Tests
    #    path: "**/test-results/**/TEST-*.xml"
    #    reporter: java-junit
  test-native:
    timeout-minutes: 60

    runs-on: ubuntu-latest
    #continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start gradle
        run: ./gradlew
      - name: Testing Kotlin/Native Linux
        run: ./gradlew --no-daemon linuxX64Test
