name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  SKIP_KORGE_SAMPLES: true

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v2 }
    - { name: Set up JDK 1.8, uses: actions/setup-java@v1, with: { java-version: 1.8 } }
    - { name: Install freeglut3 & openal, run: apt-get update && apt-get -y install freeglut3-dev libopenal-dev }
    - { name: Gradle cache, uses: ./.github/actions/gradle-cache }
    - { name: Grant execute permission for gradlew, run: chmod +x gradlew }
    - { name: Start gradle, run: ./gradlew }
    - { name: Testing JVM, run: ./gradlew jvmTest }
    - { name: Testing Node JS, run: ./gradlew jsNodeTest }
    - { name: Try building Android, run: ./gradlew publishAndroidPublicationToMavenLocal }
    - { name: Gradle cache cleanup, uses: ./.github/actions/gradle-cache-cleanup }
    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()
    #  with:
    #    name: JUnit Tests
    #    path: "**/test-results/**/TEST-*.xml"
    #    reporter: java-junit

  test-native-linux:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start gradle
        run: ./gradlew
      - name: Testing Kotlin/Native Linux
        run: ./gradlew --no-daemon linuxX64Test

  #test-native-linux-e2e:
  #  timeout-minutes: 120
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Set up JDK 1.8
  #      uses: actions/setup-java@v1
  #      with:
  #        java-version: 1.8
  #    - name: Grant execute permission for gradlew
  #      run: chmod +x gradlew
  #    - name: Start gradle
  #      run: ./gradlew
  #    - name: Publishing
  #      run: ./gradlew --no-daemon publishJvmLocal publishLinuxX64PublicationToMavenLocal
  #    - name: e2e test
  #      uses: GabrielBB/xvfb-action@v1
  #      with:
  #        run: "./gradlew runJvm runJvmCheckReferences"
  #        working-directory: e2e-test

  test-native-macos:
    timeout-minutes: 120
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start gradle
        run: ./gradlew
      - name: Testing Kotlin/Native MacosX64
        run: ./gradlew --no-daemon macosX64Test publishMacosArm64PublicationToMavenLocal

  test-native-ios:
    timeout-minutes: 120
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start gradle
        run: ./gradlew
      - name: Check compilation of iOS targets
        run: ./gradlew --no-daemon publishIosArm64PublicationToMavenLocal publishIosArm32PublicationToMavenLocal publishIosX64PublicationToMavenLocal

  test-native-macos-e2e:
    timeout-minutes: 120
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start gradle
        run: ./gradlew
      - name: Publishing
        run: ./gradlew --no-daemon publishJvmLocal publishMacosX64PublicationToMavenLocal
      - name: e2e test
        working-directory: e2e-test
        run: "./gradlew runJvmCheckReferences"
        #run: "./gradlew jvmTest runJvmCheckReferences"

  test-native-windows:
    timeout-minutes: 120
    runs-on: windows-latest
    env:
      DISABLE_JAVASCRIPT_TEST: true
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=3
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Testing Kotlin/Native MingwX64Test
        shell: cmd
        run: CALL gradlew.bat --no-daemon mingwX64Test

  test-native-windows-e2e:
    timeout-minutes: 120
    runs-on: windows-latest
    env:
      DISABLE_JAVASCRIPT_TEST: true
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=3
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: CALL gradlew.bat --no-daemon publishJvmLocal publishMingwX64PublicationToMavenLocal
        shell: cmd
      - name: e2e test
        shell: cmd
        working-directory: e2e-test
        run: "CALL gradlew.bat --no-daemon jvmTest runJvmCheckReferences"
